music_app/MusicProject/config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :show, :create]

  resource :session, only: [:new, :create, :destroy]

  resources :bands,  only: [:index, :new, :create, :edit, :show, :update, :destroy] do
    member do
        resources :albums, only: :new, as: "band_album"
    end
  end

  resources :albums, only: [:create, :edit, :show, :update, :destroy] do
    member do
        resources :tracks, only: :new, as: "album_track"
    end
  end

  resources :tracks, only: [:create, :edit, :show, :update, :destroy]

  resources :notes, only: [:edit, :create, :update, :destroy]

end

music_app/MusicProject/app/models/album.rb
class Album < ActiveRecord::Base
  validates :band_id, presence: true
  validates :title, presence: true, uniqueness: true

  belongs_to :band
  has_many :tracks, dependent: :destroy
end

music_app/MusicProject/app/models/band.rb
class Band < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true

  has_many :albums, dependent: :destroy
  has_many :tracks, through: :albums
end

music_app/MusicProject/app/models/note.rb
class Note < ActiveRecord::Base
  validates :body, :user_id, :track_id, presence: true
  belongs_to :user
  belongs_to :track
end

music_app/MusicProject/app/models/track.rb
class Track < ActiveRecord::Base
  validates :title, :album_id, presence: true

  belongs_to :album
  has_one :band, through: :album
  has_many :notes, dependent: :destroy
end

music_app/MusicProject/app/models/user.rb
class User < ActiveRecord::Base
  validates :email, :password_digest, :session_token, presence: true, uniqueness: true
  validates :password, length: { minimum: 6, allow_nil: true}

  has_many :notes
  
  attr_reader :password

  after_initialize :ensure_session_token

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)
    return nil unless user && user.is_password?(password)
    user
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest) == password
  end

  def reset_session_token
    self.session_token = SecureRandom.urlsafe_base64(16)
    self.save!
    self.session_token
  end

  private
  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64(16)
  end
end

music_app/MusicProject/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def new
    @album = Album.new(band_id: params[:id])
    @bands = Band.all
  end

  def create
    @album = Album.new(album_params)

    if @album.save
      redirect_to band_url(@album.band_id)
    else
      flash.now[:errors] = @album.errors.full_messages
      @bands = Band.all
      render :new
    end
  end

  def show
    @album = Album.find(params[:id])
  end

  def edit
    @album = Album.find(params[:id])
    @bands = Band.all
  end

  def update
    @album = Album.find(params[:id])
    if @album.update(album_params)
      redirect_to album_url(@album)
    else
      flash.now[:errors] = @album.errors.full_messages
      @bands = Band.all
      render :edit
    end
  end

  def destroy
    @album.find(params[:id]).try(:destroy)
  end

  private
  def album_params
    params.require(:album).permit(:band_id, :title, :recording_type)
  end
end

music_app/MusicProject/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user, :signed_in?, :require_login

  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def log_in(user)
    @current_user = user
    session[:session_token] = user.reset_session_token
    redirect_to bands_url
  end

  def signed_in?
    !!current_user
  end

  def log_out
    current_user.try(:reset_session_token)
    session[:session_token] = nil
  end

  def require_login
    unless signed_in?
      redirect_to new_session_url
    end
  end


end

music_app/MusicProject/app/controllers/bands_controller.rb
class BandsController < ApplicationController
  before_action :require_login

  def index
    @bands = Band.all
  end

  def new
    @band = Band.new
  end

  def create
    @band = Band.new(band_params)
    if @band.save
      redirect_to band_url(@band)
    else
      flash.now[:errors] = @band.errors.full_messages
      render :new
    end
  end

  def show
    @band = Band.find(params[:id])
  end

  def edit
    @band = Band.find(params[:id])
    render :edit
  end

  def update
    @band = Band.find(params[:id])
    @band.update(band_params)
    redirect_to band_url(@band)
  end

  def destroy
    Band.destroy(params[:id])
  end

  private

  def band_params
    params.require(:band).permit(:name)
  end

  
end

music_app/MusicProject/app/controllers/notes_controller.rb
class NotesController < ApplicationController

  def create
    @note = current_user.notes.new(note_params)
    unless @note.save
      flash[:errors] = @note.errors.full_messages
    end
    redirect_to track_url(@note.track_id)
  end

  def destroy
    @note = Note.find(params[:id])
    if @note.user == current_user
      @note.destroy
      redirect_to :back
    else
      render text: "Not allowed", status: :forbidden
    end
  end

  private
  def note_params
    note_params = params.require(:note).permit(:body, :track_id)
  end
end

music_app/MusicProject/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    render :new
  end

  def create
    @user = User.find_by_credentials(params[:user][:email],
      params[:user][:password])
    if @user
      log_in(@user)
    else
      flash.now[:errors] = "Invalid username and/or password"
      render :new
    end
  end

  def destroy
    log_out
    redirect_to new_session_url
  end
end

music_app/MusicProject/app/controllers/tracks_controller.rb
class TracksController < ApplicationController

  def new
    @track = Track.new(album_id: params[:id])
    @albums = Album.all
  end

  def create
    @track = Track.new(track_params)
    if @track.save
      redirect_to album_url(@track.album_id)
    else
      flash.now[:errors] = @track.errors.full_messages
      @albums = Album.all
      render :new
    end
  end

  def show
    @track = Track.find(params[:id])
  end

  def edit
    @track = Track.find(params[:id])
    @albums = Album.all
  end

  def update
    @track = Track.find(params[:id])
    if @track.update(track_params)
      redirect_to album_url(@track.album_id)
    else
      flash.now[:errors] = @track.errors.full_messages
      @albums = Album.all
      render :edit
    end
  end

  def destroy
    @track = Track.find(params[:id])
    album = @track.album_id
    @track.try(:destroy)
    redirect_to album_url(album)
  end

  private
  def track_params
    params.require(:track).permit(:title, :album_id)
  end
end

music_app/MusicProject/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in(@user)
      redirect_to user_url(user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    render :show
  end

  def update
  end

  def destroy
  end

  private
  def user_params
    params.require(:user).permit(:email, :password)
  end


end

music_app/MusicProject/app/helpers/albums_helper.rb
module AlbumsHelper
end

music_app/MusicProject/app/helpers/application_helper.rb
module ApplicationHelper

  def auth_token
    <<-HTML.html_safe
      <input type="hidden"
        name="authenticity_token"
        value="#{form_authenticity_token}">
    HTML
  end
end

music_app/MusicProject/app/helpers/bands_helper.rb
module BandsHelper
end

music_app/MusicProject/app/helpers/notes_helper.rb
# encoding: utf-8

module NotesHelper

  def ugly_lyrics(lyrics)
    ugly = lyrics.split("  ")
    formatted = ugly.map do |line|
      "♫ " + line
    end
    formatted = formatted.join("\n")

    <<-HTML.html_safe
    <pre>#{h(formatted)}</pre>
    HTML
  end
end

music_app/MusicProject/app/helpers/tracks_helper.rb
module TracksHelper
end

music_app/MusicProject/app/views/albums/_form.html.erb
<% action_url = (action == :new ? albums_url : album_url(@album)) %>

<form action="<%= action_url %>" method="post">
  <%= auth_token %>
  <% if action == :edit %>
    <input type="hidden" name="_method" value="patch">
  <% end %>
<label for="album_title">Album Title</label>
<input type="text"
        name="album[title]"
        value="<%= @album.title %>"
        id="album_title">
<br>
<label for="Band">Band</label>
  <select name="album[band_id]" id="Band">
  <option></option>
  <% @bands.each do |band| %>
    <option value= <%= band.id %>
      <%="selected" if band.id == @album.band_id %>>
          <%= band.name %>
    </option>
  <% end %>
  </select>
  <br>

<input type="radio" name="album[recording_type]" id="live_recording" value="Live"
  <%= "checked" if @album.recording_type == "Live" %>>
  <label for="live_recording">Live recording</label>
<input type="radio" name="album[recording_type]" id="studio_recording" value="Studio"
  <%= "checked" if @album.recording_type == "Studio" %>>
  <label for="studio_recording">Studio recording</label>
  <br>
  <input type="submit" name ="Submit">
</form>

music_app/MusicProject/app/views/albums/edit.html.erb
<h1>Edit Album</h1>

<%= render "form", band: @band, action: :edit %>

music_app/MusicProject/app/views/albums/new.html.erb
<h1>Add Album</h1>

<%= render "form", band: @band, action: :new %>

music_app/MusicProject/app/views/albums/show.html.erb
<h1><%= @album.title %></h1>
<ul>
  <li>Band: <%= link_to "#{@album.band.name}", band_url(@album.band_id)%></li>
  <li><%= button_to "Edit album", edit_album_url, method: :get %></li>
  <li><%= button_to "Delete album", albums_url, method: :delete %></li>
</ul>

<h3>Tracks</h3>
<%= button_to "Add track", new_album_track_url, method: :get%>
<br>
<ol>
  <% @album.tracks.each do |track| %>
    <li><%= link_to "#{track.title.capitalize}", track_url(track.id) %></li>
  <% end %>
</ol>

music_app/MusicProject/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MusicProject</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if signed_in? %>
Welcome <%= current_user.email %>
<%= button_to "Log Out", action= session_url, method: :delete %>
<% end %>

<% if flash[:errors] %>
  <% flash[:errors].each do |error| %>
    <div><%= error %> </div>
  <% end %>
<% end %>

<%= yield %>

</body>
</html>