goal_app/config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]

  resources :goals

  resources :comments, only: :create
end

goal_app/app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :body, :author_id, :commentable_id, :commentable_type, presence: true

  belongs_to :commentable, polymorphic: true

  belongs_to(
    :author,
    class_name: "User",
    foreign_key: :author_id
    )
end

goal_app/app/models/concerns/commentable.rb
module Commentable
  extend ActiveSupport::Concern

  included do
    has_many :comments, as: :commentable, dependent: :destroy
  end
end

goal_app/app/models/goal.rb
class Goal < ActiveRecord::Base
  include Commentable
  
  validates :title, :body, :privacy, :user_id, presence: true
  validates :completed, inclusion: { in: [true, false] }
  validates :privacy, inclusion: {in: ["Private", "Public"]}

  belongs_to(
    :author,
    class_name: "User",
    foreign_key: :user_id,
    primary_key: :id
  )

end

goal_app/app/models/user.rb
class User < ActiveRecord::Base
  include Commentable

  validates :username, :password_digest, :session_token, presence: true, uniqueness: true
  validates :password, length: { minimum: 6, allow_nil: true }

  attr_reader :password

  after_initialize :ensure_session_token

  has_many :goals

  has_many(
    :authored_comments,
    class_name: "Comment",
    foreign_key: :author_id
    )



  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    return user if user && user.is_password?(password)
    nil
  end

  def goals_for_user
    all_goals = Hash.new{|hash, key| hash[key] = []}
    self.goals.each do |goal|
      if goal.completed?
        all_goals[:complete] << goal
      else
        all_goals[:incomplete] << goal
      end
    end

    all_goals
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64(16)
    self.save!
    self.session_token
  end

  private
  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64(16)
  end

end

goal_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :signed_in?, :current_user

  def current_user
    return nil unless session[:session_token]
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def signed_in?
    !!current_user
  end

  def log_in(user)
    session[:session_token] = user.reset_session_token!
    @current_user = user
    redirect_to user_url(user)
  end

  def log_out
    current_user.try(:reset_session_token!)
    session[:session_token] = nil
    redirect_to new_session_url
  end

  def ensure_signed_in
    redirect_to new_session_url unless signed_in?
  end
end

goal_app/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = current_user.authored_comments.new(comment_params)
    unless @comment.save
      flash[:errors] = @comment.errors.full_messages
    end

    if @comment.commentable_type == "User"
      redirect_to user_url(@comment.commentable_id)
    else
      redirect_to goal_url(@comment.commentable_id)
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:body, :commentable_id, :commentable_type)
  end
end

goal_app/app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  before_action :ensure_signed_in, except: :show

  def new
    @goal = Goal.new
  end

  def create
    @goal = current_user.goals.new(goal_params)
    if @goal.save
      redirect_to goal_url(@goal)
    else
      flash.now[:errors] = @goal.errors.full_messages
      render :new
    end
  end

  def show
    @goal = Goal.find(params[:id])
    if @goal.privacy == "Private" &&
      @goal.author != current_user
      redirect_to user_url(@goal.user_id)
    end
  end

  def edit
    @goal = Goal.find(params[:id])
  end

  def update
    @goal = Goal.find(params[:id])
    if @goal.update(goal_params)
      redirect_to goal_url(@goal)
    else
      flash.now[:errors] = @goal.errors.full_messages
      render :edit
    end
  end

  def destroy
    goal = Goal.find(params[:id]).destroy
    redirect_to user_url(goal.author)
  end

  private
  def goal_params
    params.require(:goal).permit(:title, :body, :privacy, :completed)
  end
end

goal_app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
    user = User.find_by_credentials(params[:user][:username], params[:user][:password])
    if user
      log_in(user)
    else
      flash.now[:errors] = "Invalid username/password"
      render :new
    end
  end

  def destroy
    log_out
  end
end

goal_app/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    @goals = @user.goals_for_user
  end

  private
  def user_params
    params.require(:user).permit(:username, :password)
  end
end

goal_app/app/helpers/goals_helper.rb
module GoalsHelper
end

goal_app/app/views/goals/edit.html.erb
<h1>Edit goal</h1>

<form action="<%= goal_url(@goal) %>" method="post">

  <%= token_tag form_authenticity_token %>

  <input type="hidden" name="_method" value="patch">

  <label>Title<br>
  <input type="text" name="goal[title]" value="<%= @goal.title %>">
  </label><br>

  <label>Body<br>
  <textarea name="goal[body]"><%= @goal.title %></textarea>
  </label><br>

  <label>Private
    <input type="radio" name="goal[privacy]" value="Private"
    <%= "checked" unless @goal.privacy == "Public" %>>
  </label>

  <label>Public
    <input type="radio" name="goal[privacy]" value="Public"
    <%= "checked" if @goal.privacy == "Public" %>>
  </label><br>

  <input type="submit" value = "Submit">
</form>

goal_app/app/views/goals/new.html.erb
<h1>Add a goal</h1>

<form action="<%= goals_url %>" method="post">

  <%= token_tag form_authenticity_token %>

  <label>Title<br>
  <input type="text" name="goal[title]" value="<%= @goal.title %>">
  </label><br>

  <label>Body<br>
  <textarea name="goal[body]"><%= @goal.title %></textarea>
  </label><br>

  <label>Private
    <input type="radio" name="goal[privacy]" value="Private"
    <%= "checked" unless @goal.privacy == "Public" %>>
  </label>

  <label>Public
    <input type="radio" name="goal[privacy]" value="Public"
    <%= "checked" if @goal.privacy == "Public" %>>
  </label><br>

  <input type="submit" value="Submit">
</form>

goal_app/app/views/goals/show.html.erb
<h1><%= @goal.title %>
<% if @goal.completed? %>
--- Completed!
<% end %></h1>
<% if @goal.author == current_user%>
  <% if @goal.privacy == "Private" %>
    <h5>Private Goal</h5>
  <% end %>
  <br>
  <%= button_to "Edit Goal", edit_goal_url(@goal), method: :get %>
  <br>
  <%= button_to "Delete Goal", goal_url(@goal), method: :delete %>
  <br>

  <% unless @goal.completed? %>
    <form action="<%= goal_url(@goal) %>" method="post">
      <%= token_tag form_authenticity_token %>
      <input type="hidden" name="_method" value="patch">
      <input type="hidden" name="goal[completed]" value="true">
      <input type="submit" value="Goal completed!">
    </form>
  <% else %>
    <form action="<%= goal_url(@goal) %>" method="post">
      <%= token_tag form_authenticity_token %>
      <input type="hidden" name="_method" value="patch">
      <input type="hidden" name="goal[completed]" value="false">
      <input type="submit" value="Still working on it.">
    </form>
  <% end %>

<% end %>
<br>
<p> <%= @goal.body %></p>
<br>

<%= render 'comments/form', commentable: @goal %><br>

<%= render @goal.comments %>

goal_app/app/views/users/new.html.erb
<h1>New User</h1>
<form action="<%= users_url %>" method="post">
  <%= token_tag form_authenticity_token %>

  <label>Username
  <input type="text" name="user[username]">
  </label><br>

  <label>Password
  <input type="password" name="user[password]">
  </label><br>

  <input type="submit" name="some_name" value="Create User">

</form>

goal_app/app/views/users/show.html.erb
<h1><%= @user.username.capitalize %>'s page</h1>

<h2>My Goals</h2>
<br>

<h3>Incomplete Goals: <%= @goals[:incomplete].count %></h3>
<% @goals[:incomplete].each do |goal| %>
  <% if goal.privacy == "Private" %>
    <% next unless goal.author == current_user %>
  <% end %>
<%= link_to "#{goal.title}", goal_url(goal) %>
<br>
<% end %>

<h3>Completed Goals: <%= @goals[:complete].count %></h3>
<% @goals[:complete].each do |goal| %>
  <% if goal.privacy == "Private" %>
    <% next unless goal.author == current_user %>
  <% end %>
  <%= link_to "#{goal.title}", goal_url(goal) %>
  <br>
<% end %>
<br>

<%= render 'comments/form', commentable: @user %><br>

<%= render @user.comments %>