reddit_clone/config/routes.rb
Rails.application.routes.draw do
  root to: "subs#index"

  resource :session, only: [:new, :create, :destroy]

  resources :users

  resources :subs, only: [:index, :new, :create, :edit, :update, :show, :destroy]

  resources :posts, only: [:create, :edit, :show, :update, :new, :index]

  resources :comments, only: [:create, :show]
end

reddit_clone/app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :content, :author_id, :post_id, presence: true

  belongs_to :author, class_name: "User", foreign_key: :author_id

  belongs_to :post

  has_many :child_comments, foreign_key: :parent_comment_id, class_name: "Comment"

  belongs_to :parent_comment, foreign_key: :parent_comment_id, class_name: "Comment"

end

reddit_clone/app/models/post.rb
class Post < ActiveRecord::Base
  validates :title, :author_id, presence: true

  belongs_to :author, class_name: "User"

  has_many :post_subs, inverse_of: :post, dependent: :destroy

  has_many :subs, through: :post_subs, source: :sub

  has_many :comments, inverse_of: :post

  def comments_by_parent_id
    all_comments = self.comments.includes(:author)
    hash_comments = Hash.new { [] }

    all_comments.each do |comment|
      hash_comments[comment.parent_comment_id] += [comment]
    end
    hash_comments
  end

end
#
# post_params
#
# post_sub_params
#
# post = Post.new(post_params)
# post_sub = post.post_subs.new(post_sub_params)
# post.save
#
#
# post_sub.post #
#
# class PostSub
#
#   validates :post, presence: true
#
# end
#

reddit_clone/app/models/post_sub.rb
class PostSub < ActiveRecord::Base
  validates :post, :sub_id, presence: true
  belongs_to :post
  belongs_to :sub
end

reddit_clone/app/models/sub.rb
class Sub < ActiveRecord::Base
  validates :title, :description, :moderator_id, presence: true
  validates :moderator_id, numericality: true

  has_many :post_subs, dependent: :destroy

  has_many :posts, through: :post_subs, source: :post

  belongs_to :moderator, class_name: "User", foreign_key: :moderator_id
end

reddit_clone/app/models/user.rb
class User < ActiveRecord::Base
  validates :username, :password_digest, :session_token, presence: true, uniqueness: true
  validates :password, length: {minimum: 6, allow_nil: true}

  attr_reader :password

  has_many :posts, foreign_key: :author_id

  has_many :subs, foreign_key: :moderator_id

  has_many :comments, foreign_key: :author_id

  after_initialize :ensure_session_token

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    return nil unless user && user.valid_password?(password)
    user
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def valid_password?(password)
    BCrypt::Password.new(self.password_digest) == password
  end

  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64(16)
    self.save!
    self.session_token
  end


  private
  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64(16)
  end
end

reddit_clone/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :signed_in?

  def log_out!(user)
    user.reset_session_token!
    session[:token] = nil
    redirect_to new_session_url
  end

  def log_in!(user)
    session[:token] = user.reset_session_token!
    @current_user = user
    redirect_to user_url(user)
  end

  def current_user
    @current_user ||= User.find_by(session_token: session[:token])
  end

  def signed_in?
    !!current_user
  end

  def require_signed_in
    redirect_to new_session_url unless signed_in?
  end

end

reddit_clone/app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :require_signed_in, only: [:create]

  def create
    @comment = current_user.comments.new(comment_params)
    if @comment.save
      redirect_to post_url(@comment.post_id)
    else
      flash[:errors] = @comment.errors.full_messages
      redirect_to :back
    end
  end


  def show
    @comment = Comment.find(params[:id])
  end

  private
  def comment_params
    params.require(:comment).permit(:parent_comment_id, :content, :post_id)
  end

end

reddit_clone/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_signed_in
  before_action :require_author, only: [:edit, :update]

  def new
    @post = current_user.posts.new
  end

  def create
    @post = current_user.posts.new(post_params)
    @post.sub_ids = params[:post][:sub_ids]
    if @post.save
      redirect_to post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.sub_ids = params[:post][:sub_ids]
    if @post.update(post_params)
      redirect_to post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :edit
    end
  end

  def show
    @post = Post.find(params[:id])
    @hash_comments = @post.comments_by_parent_id
    end

  def index

  end

  def destroy

  end



  private
  def post_params
    params.require(:post).permit(:title, :content, :url)
  end

  def require_author
    @post = Post.find(params[:id])
    redirect_to :back unless @post.author == current_user
  end

end

reddit_clone/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    render :new
  end


  def create
    @user = User.find_by_credentials(params[:user][:username], params[:user][:password])
    unless @user
      flash.now[:errors] = "Invalid username or password"
      render :new
    else
      log_in!(@user)
    end
  end

  def destroy
    user = User.find_by(session_token: session[:token])
    log_out!(user)
  end



end

reddit_clone/app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_action :require_moderator, except: [:show, :index]

  def new
    @sub = current_user.subs.new
  end

  def create
    @sub = current_user.subs.new(sub_params)
    if @sub.save
      redirect_to subs_url
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :new
    end
  end

  def edit
    @sub = Sub.find(params[:id])
  end

  def update
    @sub = Sub.find(params[:id])
    if @sub.update(sub_params)
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :edit
    end
  end

  def destroy
  end

  def index
    @subs = Sub.all
  end

  def show
    @sub = Sub.find(params[:id])
  end

  def require_moderator
    redirect_to :back unless current_user.moderator_status?
  end

  private
  def sub_params
    params.require(:sub).permit(:title, :description)
  end


end

reddit_clone/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in!(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :edit
    end
  end

  def show
    @user = User.find(params[:id])
  end


private

  def user_params
    params.require(:user).permit(:username, :password)
  end

end

reddit_clone/app/helpers/application_helper.rb
module ApplicationHelper

  def auth_token
    <<-HTML.html_safe
      <input type="hidden"
              value="#{h(form_authenticity_token)}"
              name="authenticity_token">
    HTML
  end
end

reddit_clone/app/helpers/subs_helper.rb
module SubsHelper
end

reddit_clone/app/views/comments/_comment.html.erb
<li><%= link_to "#{comment.content}", comment_url(comment)  %>
  <ol>
  <% @hash_comments[comment.id].each do |comment| %>
    <%= render comment %>
  <% end %>
  </ol>

reddit_clone/app/views/comments/_form.html.erb
<form action="<%= comments_url %>" method="post">
<%= auth_token %>
  <label for="content"> Content </label>
  <input type="textarea" name="comment[content]" value="" id="content">
  <br>
  <% if parent_comment %>
    <input type="hidden" name="comment[parent_comment_id]" value="<%= parent_comment.id %>">
    <input type="hidden" name="comment[post_id]" value="<%= parent_comment.post_id %>">
  <% else %>
    <input type="hidden" name="comment[post_id]" value="<%= post_id %>">
  <% end %>
  <input type="submit" value="Add Comment">
</form>

reddit_clone/app/views/comments/show.html.erb
<%= @comment.content %>

<%= render "form", parent_comment: @comment %>

reddit_clone/app/views/subs/_form.html.erb
<% action_url = (action == :new ? subs_url : sub_url(@sub)) %>


<form action="<%= action %>" method="post">
  <%= auth_token %>
  <% if action == :edit %>
    <input type="hidden" name="_method" value="patch">
  <% end %>

  <label for="title"> Title </label>
  <input type="text" value="<%= @sub.title %>" name="sub[title]" id="title">
  <br>
  <label for="description"> Description </label>
  <input type="text" value="<%= @sub.title %>" name="sub[title]" id="description">
  <br>
  <input type="submit" value="Create Sub">


</form>

reddit_clone/app/views/subs/_sub.html.erb
<li>  <a href="<%= sub_url(sub) %>"> <%= sub.title.capitalize %> </a>
<li>Description: <%= sub.description %>
<li>Moderator: <%= sub.moderator.username %>

reddit_clone/app/views/subs/edit.html.erb
<h1>Update <%= @sub.title %></h1>

<%= render "form", sub: @sub, action: :edit %>

reddit_clone/app/views/subs/index.html.erb
<h1>All Subs</h1>
<ul>
<% @subs.each do |sub| %>
  <%= render sub %>
<% end %>
</ul>

reddit_clone/app/views/subs/new.html.erb
<h1> Create a Sub </h1>
<%= render "form", sub: @sub, action: :new %>

reddit_clone/app/views/subs/show.html.erb
<a href="<%= new_post_url %>"> Add a New Post </a>
<br>
<% @sub.posts.each do |post| %>
  <%= link_to "#{post.title}", post_url(post) %>
<% end %>